spring:
  application:
    name: Project_Management
  datasource:
    url: jdbc:postgresql://localhost:5432/security_test
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
app:
  jwt-secret: JWTSecretKey
  jwt-expiration-milliseconds: 60480000

